import { z } from "zod";
import { GRID_CELLS, type EcologyFrame, type SimulationState } from "./world";
import type { SetupAnswers } from "./setup";
import { ACTIVATIONS, DURATIONS, TRANSITIONS, scheduledRuleChangeSchema, type ScheduledRuleChange, type WorldRuleGraph } from "./rules";

export const PREY_STRATEGIES=["efficient_grazing","early_brood","armored","swarming","dispersal"] as const;
export const PREDATOR_STRATEGIES=["ambush","pursuit","pack_hunting","efficient_kill","brood_hunting"] as const;
export const MUTATION_TARGETS=["metabolism","fecundity","mobility","defense","sensing"] as const;
export const MUTATION_TEMPOS=["slow","steady","rapid"] as const;
export const ENVIRONMENT_PRESSURES=["nutrient_bloom","drought","toxin_wave","heat_wave","fragmentation","stability"] as const;
export const INTENSITIES=["low","medium","high"] as const;
export const EVOLUTION_TRIGGERS=["prey_crash","predator_crash","resource_shift","speciation","predation_spike","stagnation"] as const;
export type PreyStrategy=typeof PREY_STRATEGIES[number]; export type PredatorStrategy=typeof PREDATOR_STRATEGIES[number]; export type MutationTarget=typeof MUTATION_TARGETS[number]; export type MutationTempo=typeof MUTATION_TEMPOS[number]; export type EnvironmentPressure=typeof ENVIRONMENT_PRESSURES[number]; export type Intensity=typeof INTENSITIES[number]; export type EvolutionTrigger=typeof EVOLUTION_TRIGGERS[number]; export type DecisionSource="jev"|"fallback";
export type DecisionAnswer<T extends string>={choice:T;confidence:number;probabilities:Record<T,number>};
export type EcologyObservation={generation:number;prey:number;predators:number;preyDelta12:number;predatorDelta12:number;kills12:number;resourceMean:number;resourceDelta12:number;speciesRichness:number;speciesDelta12:number;meanPreyEnergy:number;meanPredatorEnergy:number};
export type EcologySummary={generation:number;trigger:EvolutionTrigger;intent:SetupAnswers;environment:SimulationState["config"]["environment"];objective:SimulationState["config"]["fitness"];rules?:WorldRuleGraph;observation:EcologyObservation};
export type EvolutionDecision={generation:number;trigger:EvolutionTrigger;observationHash:string;source:DecisionSource;model?:string;usage?:{input_tokens:number;output_tokens:number};ruleGraphVersion?:number;scheduledRuleChange?:ScheduledRuleChange;ruleActivation?:DecisionAnswer<typeof ACTIVATIONS[number]>;ruleDuration?:DecisionAnswer<typeof DURATIONS[number]>;ruleTransition?:DecisionAnswer<typeof TRANSITIONS[number]>;preyStrategy:DecisionAnswer<PreyStrategy>;predatorStrategy:DecisionAnswer<PredatorStrategy>;preyMutationTarget:DecisionAnswer<MutationTarget>;preyMutationTempo:DecisionAnswer<MutationTempo>;predatorMutationTarget:DecisionAnswer<MutationTarget>;predatorMutationTempo:DecisionAnswer<MutationTempo>;environmentPressure:DecisionAnswer<EnvironmentPressure>;environmentIntensity:DecisionAnswer<Intensity>};
export type EvolutionLedger=EvolutionDecision[];
const probability=z.number().finite().min(0).max(1); const normalized=(v:Record<string,number>)=>Math.abs(Object.values(v).reduce((a,b)=>a+b,0)-1)<=.011;
function answerSchema<const T extends readonly [string,...string[]]>(options:T){return z.object({choice:z.enum(options),confidence:probability,probabilities:z.record(z.enum(options),probability).refine(v=>Object.keys(v).length===options.length&&normalized(v),"probabilities must cover all choices and sum to one")}).strict().superRefine((a,c)=>{const values=Object.values(a.probabilities) as number[];if(a.probabilities[a.choice]!==Math.max(...values))c.addIssue({code:"custom",message:"selected choice must have maximum probability"});});}
const schema=z.object({generation:z.number().int().min(12).max(180),trigger:z.enum(EVOLUTION_TRIGGERS),observationHash:z.string().regex(/^eco_[a-z0-9]+$/),source:z.enum(["jev","fallback"]),model:z.string().min(1).max(100).optional(),usage:z.object({input_tokens:z.number().int().nonnegative(),output_tokens:z.number().int().nonnegative()}).strict().optional(),ruleGraphVersion:z.number().int().min(1).optional(),scheduledRuleChange:scheduledRuleChangeSchema.optional(),ruleActivation:answerSchema(ACTIVATIONS).optional(),ruleDuration:answerSchema(DURATIONS).optional(),ruleTransition:answerSchema(TRANSITIONS).optional(),preyStrategy:answerSchema(PREY_STRATEGIES),predatorStrategy:answerSchema(PREDATOR_STRATEGIES),preyMutationTarget:answerSchema(MUTATION_TARGETS),preyMutationTempo:answerSchema(MUTATION_TEMPOS),predatorMutationTarget:answerSchema(MUTATION_TARGETS),predatorMutationTempo:answerSchema(MUTATION_TEMPOS),environmentPressure:answerSchema(ENVIRONMENT_PRESSURES),environmentIntensity:answerSchema(INTENSITIES)}).strict();
function fnv(text:string){let h=0x811c9dc5;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,0x01000193);}return(h>>>0).toString(36);}
export function observationHash(o:EcologyObservation){return`eco_${fnv(JSON.stringify(o))}`;}
function round(v:number){return Math.round(v*100)/100;} function frameAt(state:SimulationState,generation:number):EcologyFrame{return state.history.reduce((best,f)=>Math.abs(f.generation-generation)<Math.abs(best.generation-generation)?f:best,state.history[0]);}
export function ecologyObservation(state:SimulationState):EcologyObservation{const prior=frameAt(state,Math.max(0,state.generation-12));let preyEnergy=0,predEnergy=0;for(let i=0;i<GRID_CELLS;i++){if(state.guild[i]===1)preyEnergy+=state.energy[i];if(state.guild[i]===2)predEnergy+=state.energy[i];}return Object.freeze({generation:state.generation,prey:state.stats.prey,predators:state.stats.predators,preyDelta12:state.stats.prey-prior.prey,predatorDelta12:state.stats.predators-prior.predators,kills12:state.stats.kills-prior.kills,resourceMean:round(state.stats.resources/GRID_CELLS),resourceDelta12:round((state.stats.resources-prior.resources)/GRID_CELLS),speciesRichness:state.stats.speciesRichness,speciesDelta12:state.stats.speciesRichness-prior.speciesRichness,meanPreyEnergy:round(preyEnergy/(state.stats.prey||1)),meanPredatorEnergy:round(predEnergy/(state.stats.predators||1))});}
export function detectEvolutionTrigger(state:SimulationState,ledger:readonly EvolutionDecision[]):EvolutionTrigger|null{if(state.generation<12||ledger.length>=8)return null;const last=ledger.at(-1)?.generation??0;if(ledger.length&&state.generation-last<12)return null;const o=ecologyObservation(state);if(o.prey>0&&o.preyDelta12<=-Math.max(5,Math.round((o.prey-o.preyDelta12)*.3)))return"prey_crash";const previousPredators=o.predators-o.predatorDelta12,hadPredators=state.history.some(frame=>frame.predators>0);if((o.predators===0&&hadPredators)||(o.predators>0&&o.predatorDelta12<=-Math.max(2,Math.round(previousPredators*.35))))return"predator_crash";if(Math.abs(o.resourceDelta12)>=18)return"resource_shift";if(o.speciesDelta12>=2)return"speciation";if(o.kills12>=Math.max(3,Math.round(o.prey*.16)))return"predation_spike";if(state.generation-last>=30)return"stagnation";return null;}
export function summarizeEcology(state:SimulationState,intent:SetupAnswers,trigger:EvolutionTrigger):EcologySummary{return Object.freeze({generation:state.generation,trigger,intent:Object.freeze({...intent}),environment:Object.freeze({...state.config.environment}),objective:Object.freeze({...state.config.fitness}),rules:structuredClone(state.config.rules!),observation:ecologyObservation(state)});}
export function validateEvolutionDecision(input:unknown):EvolutionDecision{const p=schema.safeParse(input);if(!p.success)throw new Error("Invalid evolution decision");const decision=p.data as EvolutionDecision,change=decision.scheduledRuleChange;if(change){if(change.decidedAtGeneration!==decision.generation||decision.ruleGraphVersion===undefined)throw new Error("Invalid scheduled rule binding");if(decision.ruleActivation?.choice!==change.activation||decision.ruleDuration?.choice!==change.duration||decision.ruleTransition?.choice!==change.transition)throw new Error("Scheduled rule evidence mismatch");if(change.patch.kind==="environment"&&change.patch.field==="pressure"&&decision.environmentPressure.choice!==change.patch.value)throw new Error("Scheduled pressure mismatch");}return decision;}
function certain<T extends string>(choice:T,options:readonly T[]):DecisionAnswer<T>{return{choice,confidence:1,probabilities:Object.fromEntries(options.map(v=>[v,v===choice?1:0])) as Record<T,number>};}
export function deterministicEvolutionDecision(s:EcologySummary):EvolutionDecision{
  const prey:PreyStrategy=s.trigger==="prey_crash"?"early_brood":s.trigger==="predation_spike"?"armored":s.observation.resourceDelta12<0?"efficient_grazing":"dispersal";
  const predator:PredatorStrategy=s.trigger==="predator_crash"?"efficient_kill":s.trigger==="predation_spike"?"ambush":s.observation.prey>80?"pack_hunting":"pursuit";
  const pressure:EnvironmentPressure=s.trigger==="resource_shift"&&s.observation.resourceDelta12<0?"nutrient_bloom":s.trigger==="prey_crash"?"stability":s.trigger==="predation_spike"?"fragmentation":s.environment.hazard==="toxin"?"toxin_wave":s.environment.hazard==="heat"?"heat_wave":"drought";
  const activation=s.trigger==="resource_shift"&&s.observation.resourceDelta12<0?"resources_low":s.trigger==="predator_crash"||s.trigger==="prey_crash"?"after_6":"after_12";
  return validateEvolutionDecision({generation:s.generation,trigger:s.trigger,observationHash:observationHash(s.observation),source:"fallback",ruleGraphVersion:s.rules?.version??1,scheduledRuleChange:{decidedAtGeneration:s.generation,activation,duration:"medium",transition:"ramp",patch:{kind:"environment",field:"pressure",value:pressure}},ruleActivation:certain(activation,ACTIVATIONS),ruleDuration:certain("medium",DURATIONS),ruleTransition:certain("ramp",TRANSITIONS),preyStrategy:certain(prey,PREY_STRATEGIES),predatorStrategy:certain(predator,PREDATOR_STRATEGIES),preyMutationTarget:certain(s.trigger==="predation_spike"?"defense":"fecundity",MUTATION_TARGETS),preyMutationTempo:certain(s.trigger==="speciation"?"slow":"steady",MUTATION_TEMPOS),predatorMutationTarget:certain(s.trigger==="predator_crash"?"metabolism":"sensing",MUTATION_TARGETS),predatorMutationTempo:certain("steady",MUTATION_TEMPOS),environmentPressure:certain(pressure,ENVIRONMENT_PRESSURES),environmentIntensity:certain(s.trigger==="prey_crash"?"low":"medium",INTENSITIES)});
}
