import {describe,it,expect} from 'vitest';
import {createSimulation,stepSimulation,LEGACY_ENGINE_VERSION,type OrganismSeed,type SimulationState} from './world';
import {defaultConfig} from './setup';
import {deterministicEvolutionDecision,summarizeEcology} from './decisions';
const founder:OrganismSeed={x:10,y:10,guild:'prey',ruleSpecies:1,energy:50,lineage:1,species:1,generation:0,strategy:'efficient_grazing',traits:[128,128,0,128,128]};
const energy=(s:SimulationState)=>Array.from(s.energy).reduce((sum,e,i)=>sum+(s.guild[i]?e:0),0);
function cluster(hunter=false,mutual=false,legacy=false){const config=defaultConfig();config.environment.abundance='scarce';config.fitness.cooperate=1;config.rules!.species.forEach(s=>{s.selfInteraction='cooperative';s.role=hunter?'hunter':'grazer';});if(hunter){config.rules!.species.push({id:'C',role:'grazer',selfInteraction:'neutral'});config.rules!.interactions.push({pair:'A:C',mode:'neutral'},{pair:'B:C',mode:'neutral'});}config.rules!.interactions.forEach(p=>p.mode=mutual?'mutualism':'neutral');const population=Array.from({length:9},(_,i)=>({...founder,x:10+i%3,y:10+Math.floor(i/3),lineage:i+1,ruleSpecies:mutual?1+i%2:1,guild:hunter?'predator' as const:'prey' as const,strategy:hunter?'ambush' as const:'efficient_grazing' as const}));const state=createSimulation({seed:1,config,initialPopulation:population,engineVersion:legacy?LEGACY_ENGINE_VERSION:undefined});state.resources.fill(0);return state;}
describe('ca8 energy budgets',()=>{
 for(const hunter of [false,true])for(const mutual of [false,true])it(`does not manufacture energy from ${mutual?'mutualism':'cooperation'} in ${hunter?'hunters':'basal feeders'}`,()=>{const s=cluster(hunter,mutual),n=stepSimulation(s);const input=n.events.filter(e=>e.kind==='feeding').reduce((sum,e)=>sum+e.energy,0);expect(n.stats.births).toBe(0);expect(energy(n)).toBeLessThan(energy(s)+input);if(hunter)expect(input).toBe(0);});
 it('retains the legacy negative-cost reproduction for old recordings',()=>{const s=cluster(false,false,true),n=stepSimulation(s);expect(energy(n)).toBeGreaterThan(energy(s)+n.events.filter(e=>e.kind==='feeding').reduce((sum,e)=>sum+e.energy,0));});
 it('retains territorial expenditure instead of clamping penalties away',()=>{const s=cluster(true);const territorial=structuredClone(s);territorial.config.rules!.species[0].selfInteraction='territorial';expect(energy(stepSimulation(territorial))).toBeLessThan(energy(stepSimulation(s)));});
 it('funds offspring from their parent budget',()=>{const s=createSimulation({seed:10,config:defaultConfig(),initialPopulation:[{...founder,strategy:'early_brood',energy:220}]});const n=stepSimulation(s);expect(n.stats.births).toBe(1);const input=n.events.filter(e=>e.kind==='feeding').reduce((sum,e)=>sum+e.energy,0);expect(energy(n)).toBeLessThan(energy(s)+input);const birth=n.events.find(e=>e.kind==='birth')!;expect(n.energy[birth.at]).toBeCloseTo(birth.energy);});
 it('credits predation from the remaining captured budget, not pre-birth energy',()=>{const config=defaultConfig();config.rules!.species[0].selfInteraction='neutral';const s=createSimulation({seed:1,config,initialPopulation:[{...founder,strategy:'early_brood',energy:220},{...founder,x:11,guild:'predator',ruleSpecies:2,strategy:'efficient_kill',energy:100,lineage:2}]});const n=stepSimulation(s);const death=n.events.find(e=>e.kind==='death'&&e.cause==='predation')!;const feeding=n.events.find(e=>e.kind==='feeding'&&e.source==='prey')!;expect(n.stats.kills).toBe(1);expect(n.stats.births).toBeGreaterThan(0);expect(death.energy).toBeLessThan(220);expect(feeding.energy).toBeCloseTo(death.energy*.8);expect(feeding.energy).toBeLessThanOrEqual(death.energy);});
});
describe('extinction activation history',()=>{
 function proposal(s:SimulationState){const d=deterministicEvolutionDecision(summarizeEcology(s,{world:'pond',threat:'drought',reward:'observe'},'stagnation'));d.ruleGraphVersion=1;d.scheduledRuleChange={decidedAtGeneration:12,activation:'species_extinction',duration:'persistent',transition:'abrupt',patch:{kind:'environment',field:'pressure',value:'drought'}};return d;}
 it('does not treat a never-populated slot as extinct',()=>{const s=createSimulation({seed:1,config:defaultConfig(),initialPopulation:[founder]});s.generation=12;expect(stepSimulation(s,proposal(s)).appliedRuleChanges).toEqual([]);});
 it('activates only after a populated slot disappears',()=>{let s=createSimulation({seed:1,config:defaultConfig(),initialPopulation:[founder,{...founder,x:30,guild:'predator',ruleSpecies:2,strategy:'ambush',energy:1,lineage:2}]});s=stepSimulation(s);expect(s.stats.predators).toBe(0);s.generation=12;expect(stepSimulation(s,proposal(s)).appliedRuleChanges).toEqual([12]);});
 it('preserves ca7 activation even for a never-populated slot',()=>{const s=createSimulation({seed:1,config:defaultConfig(),initialPopulation:[founder],engineVersion:LEGACY_ENGINE_VERSION});s.generation=12;expect(stepSimulation(s,proposal(s)).appliedRuleChanges).toEqual([12]);});
});
