import { DEFAULT_GENERATIONS, stepSimulation, type SimulationState } from "./world";
import { detectEvolutionTrigger, deterministicEvolutionDecision, observationHash, summarizeEcology, validateEvolutionDecision, type EcologySummary, type EvolutionDecision, type EvolutionLedger } from "./decisions";
import type { SetupAnswers } from "./setup";
export type EvolutionDecider=(summary:EcologySummary)=>Promise<unknown>;
export function validateEvolutionLedger(input:unknown):EvolutionLedger{if(!Array.isArray(input)||input.length>8)throw new Error("Invalid evolution decision ledger");const ledger=input.map(validateEvolutionDecision);for(let i=1;i<ledger.length;i++)if(ledger[i].generation-ledger[i-1].generation<12)throw new Error("Invalid evolution decision ledger order or cooldown");return ledger;}
export function activeDecisionForGeneration(ledger:readonly EvolutionDecision[],generation:number){let active:EvolutionDecision|undefined;for(const d of ledger){if(d.generation>generation)break;active=d;}return active;}
function exactDecision(state:SimulationState,intent:SetupAnswers,trigger:ReturnType<typeof detectEvolutionTrigger>,candidate:EvolutionDecision){if(!trigger)throw new Error("No trigger");const summary=summarizeEcology(state,intent,trigger);if(candidate.generation!==state.generation||candidate.trigger!==trigger||candidate.observationHash!==observationHash(summary.observation)||candidate.ruleGraphVersion!==state.config.rules?.version)throw new Error("Decision does not match frozen observation or rule graph");return candidate;}
export function advanceUntilDecisionTrigger(state:SimulationState,ledger:readonly EvolutionDecision[],maxSteps:number):SimulationState{let next=state;for(let i=0;i<Math.max(0,Math.floor(maxSteps))&&next.outcome==="running";i++){const trigger=detectEvolutionTrigger(next,ledger.filter(d=>d.generation<=next.generation));if(trigger&&!ledger.some(d=>d.generation===next.generation))break;next=stepSimulation(next,activeDecisionForGeneration(ledger,next.generation),ledger);}return next;}
export const advanceUntilDecisionEpoch=advanceUntilDecisionTrigger;
export async function runFreshWithDecisions(initial:SimulationState,intent:SetupAnswers,decide:EvolutionDecider,generations=DEFAULT_GENERATIONS):Promise<{state:SimulationState;ledger:EvolutionLedger}>{let state=initial;const ledger:EvolutionLedger=[];const target=Math.min(DEFAULT_GENERATIONS,state.generation+Math.max(0,Math.floor(generations)));while(state.generation<target&&state.outcome==="running"){const trigger=detectEvolutionTrigger(state,ledger);if(trigger){const summary=summarizeEcology(state,intent,trigger);let decision:EvolutionDecision;try{decision=exactDecision(state,intent,trigger,validateEvolutionDecision(await decide(summary)));}catch{decision=deterministicEvolutionDecision(summary);}ledger.push(decision);}state=stepSimulation(state,activeDecisionForGeneration(ledger,state.generation),ledger);}return{state,ledger};}
export function runWithDecisionLedger(initial:SimulationState,input:unknown,generations=DEFAULT_GENERATIONS,intent:SetupAnswers={world:"replay",threat:"replay",reward:"replay"}):SimulationState{const ledger=validateEvolutionLedger(input);let state=initial,index=0;const accepted:EvolutionLedger=[];const target=Math.min(DEFAULT_GENERATIONS,state.generation+Math.max(0,Math.floor(generations)));while(state.generation<target&&state.outcome==="running"){const trigger=detectEvolutionTrigger(state,accepted);if(trigger){const decision=ledger[index];if(!decision)throw new Error(`Replay is missing ${trigger} decision at generation ${state.generation}`);exactDecision(state,intent,trigger,decision);accepted.push(decision);index++;}else if(ledger[index]?.generation===state.generation)throw new Error("Replay decision is reordered or has no canonical trigger");state=stepSimulation(state,activeDecisionForGeneration(accepted,state.generation),accepted);}if(index!==ledger.length)throw new Error("Replay contains unreachable or reordered decisions");return state;}
