import {expect,it,vi} from "vitest";
import {CouncilProtocolViolation} from "./runtime-correction";
import {runCouncil,selectCouncil,type CouncilClient} from "./council-service";
import {defaultConfig} from "@/game/setup";
import {createSimulation} from "@/game/world";
import {summarizeEcology,validateSpeciesDirectives} from "@/game/decisions";
function summary(){const config=defaultConfig();config.rules!.council={version:1,members:[{id:"birth_A",responsibility:"birth_policy",scope:"A",activation:"always"},{id:"self_A",responsibility:"self_interaction",scope:"A",activation:"always"}]};return {...summarizeEcology(createSimulation({seed:1,config}),{world:"pond",threat:"drought",reward:"coexist"},"stagnation"),generation:12};}
function response(request:Parameters<CouncilClient["systemOne"]>[0]){return {model:"fixture",usage:{input_tokens:10,output_tokens:2},answers:Object.fromEntries(Object.entries(request.questions).map(([key,q])=>{const keys=Object.keys(q.criteria),choice=key==="selectedPatch"?"none":keys[0];return [key,{type:"choice" as const,choice,confidence:.8,probabilities:Object.fromEntries(keys.map(k=>[k,k===choice?1:0]))}]}))};}
function collide(probabilities:Record<string,number>){const original=Object.keys(probabilities).sort().join(),zero=Object.keys(probabilities).filter(k=>probabilities[k]===0).sort();probabilities[zero[0]+","+zero[1]]=0;delete probabilities[zero[0]];delete probabilities[zero[1]];expect(Object.keys(probabilities).sort().join()).toBe(original);}
it.each(["orchestrator","specialists"])("rejects persistent comma-aliased palette in %s within the shared allowance",async stage=>{let calls=0;const reserve=vi.fn();await expect(runCouncil(summary(),{async systemOne(request){calls++;const raw=response(request),key=stage==="orchestrator"?"activation":"birth_A__strategy";if(raw.answers[key])collide(raw.answers[key].probabilities);return raw;}},reserve)).rejects.toThrow(CouncilProtocolViolation);expect(calls).toBe(stage==="orchestrator"?2:3);expect(reserve).toHaveBeenCalledTimes(calls);});
it("rejects comma-aliased archived council evidence independently of provider validation",async()=>{const s=summary(),decision=await runCouncil(s,{async systemOne(request){return response(request);}});collide(decision.council!.orchestrator.evidence.activation.probabilities);expect(()=>validateSpeciesDirectives(decision,s.rules!)).toThrow("Invalid council evidence palette");});
it("rejects comma-aliased setup council palettes without extending setup retry authority",async()=>{const s=summary();let calls=0;await expect(selectCouncil(s.rules!,s.intent,{async systemOne(request){calls++;const raw=response(request);collide(raw.answers.count.probabilities);return raw;}})).rejects.toThrow("Council scope palette mismatch");expect(calls).toBe(1);});
it.each(["orchestrator","specialists"])("accepts fresh authored correction for a comma-aliased %s palette without rewriting it",async stage=>{const s=summary(),frozen=JSON.stringify(s),requests:Parameters<CouncilClient["systemOne"]>[0][]=[],reserve=vi.fn();let accepted:ReturnType<typeof response>["answers"][string]|undefined;const key=stage==="orchestrator"?"activation":"birth_A__strategy",badCall=stage==="orchestrator"?1:2;const decision=await runCouncil(s,{async systemOne(request){requests.push(request);const raw=response(request);if(requests.length===badCall)collide(raw.answers[key].probabilities);if(requests.length===badCall+1){const a=raw.answers[key],chosen=stage==="orchestrator"?"after_24":"armored",keys=Object.keys(a.probabilities).reverse();a.choice=chosen;a.probabilities=Object.fromEntries(keys.map(k=>[k,k===chosen?.8:.2/(keys.length-1)]));accepted=structuredClone(a);}return raw;}},reserve);expect(requests).toHaveLength(3);expect(reserve).toHaveBeenCalledTimes(3);expect(requests[badCall].questions).toEqual(requests[badCall-1].questions);expect(requests[badCall].state).toMatchObject({protocol_correction:{issues:[{code:"protocol",reason:"scope_palette_mismatch"}]}});expect(JSON.stringify(s)).toBe(frozen);expect(decision.council?.correction).toEqual({attempts:1,stage,rejectedUsage:{input_tokens:10,output_tokens:2}});expect(decision.usage).toEqual({input_tokens:30,output_tokens:6});const {type,...evidence}=accepted!;expect(type).toBe("choice");expect(stage==="orchestrator"?decision.council!.orchestrator.evidence.activation:decision.speciesDirectives![0].strategy).toEqual(evidence);expect(()=>validateSpeciesDirectives(decision,s.rules!)).not.toThrow();});
