import {expect,it,vi} from "vitest";
import {z} from "zod";
import * as decisions from "@/game/decisions";
import {runCouncil,type CouncilClient} from "./council-service";
import {createCallBudget} from "./route";
import {defaultConfig} from "@/game/setup";
import {createSimulation} from "@/game/world";
function summary(){const config=defaultConfig();config.rules!.council={version:1,members:[{id:"birth_A",responsibility:"birth_policy",scope:"A",activation:"always"},{id:"self_A",responsibility:"self_interaction",scope:"A",activation:"always"}]};return {...decisions.summarizeEcology(createSimulation({seed:1,config}),{world:"pond",threat:"drought",reward:"coexist"},"stagnation"),generation:12};}
function response(request:Parameters<CouncilClient["systemOne"]>[0]){return {model:"fixture",usage:{input_tokens:10,output_tokens:2},answers:Object.fromEntries(Object.entries(request.questions).map(([key,q])=>{const keys=Object.keys(q.criteria),choice=key==="selectedPatch"?"none":keys[0];return [key,{type:"choice" as const,choice,confidence:.8,probabilities:Object.fromEntries(keys.map(k=>[k,k===choice?1:0]))}]}))};}
it("bounds two repair-heavy workflow reservations and resets only after the window",async()=>{
 let clock=0,calls=0;const reserve=createCallBudget(60,60000,()=>clock);const stage=async()=>{await reserve("client");calls++;};const checkpoint=async()=>{let local=0;return runCouncil(summary(),{async systemOne(request){calls++;local++;const raw=response(request);if(local===1)raw.answers.activation.confidence=2;return raw;}},()=>reserve("client"));};
 // Setup/reflection reservations represent their established 13+1 worst-case requests.
 for(let i=0;i<13;i++)await stage();for(let i=0;i<8;i++)await checkpoint();await stage();expect(calls).toBe(38);
 for(let i=0;i<13;i++)await stage();for(let i=0;i<3;i++)await checkpoint();expect(calls).toBe(60);await expect(checkpoint()).rejects.toThrow("quota exceeded");expect(calls).toBe(60);clock=59999;await expect(checkpoint()).rejects.toThrow("quota exceeded");expect(calls).toBe(60);clock=60000;await checkpoint();expect(calls).toBe(63);
});
it.each(["fractional","missing","nan","empty_model"])("does not correct unaccountable %s metadata",async(mode)=>{let calls=0;await expect(runCouncil(summary(),{async systemOne(request){calls++;const raw=response(request);if(mode==="fractional")raw.usage.input_tokens=.5;if(mode==="missing")delete (raw as Partial<typeof raw>).usage;if(mode==="nan")raw.usage.input_tokens=NaN;if(mode==="empty_model")raw.model="";return raw;}})).rejects.toThrow();expect(calls).toBe(1);});
it("does not retry a schema exception thrown by provider transport",async()=>{const request=vi.fn().mockRejectedValue(new z.ZodError([]));await expect(runCouncil(summary(),{systemOne:request})).rejects.toThrow();expect(request).toHaveBeenCalledTimes(1);});
it("does not retry an internal final reconciliation failure",async()=>{const reconciliation=vi.spyOn(decisions,"validateEvolutionDecision").mockImplementation(()=>{throw new Error("Internal reconciliation failure");});let calls=0;try{await expect(runCouncil(summary(),{async systemOne(request){calls++;return response(request);}})).rejects.toThrow("Internal reconciliation failure");expect(calls).toBe(2);}finally{reconciliation.mockRestore();}});
it.each([false,true])("keeps all-inactive calls bounded, corrected=%s",async(corrected)=>{let calls=0;const result=await runCouncil(summary(),{async systemOne(request){calls++;const raw=response(request);for(const [key,a] of Object.entries(raw.answers))if(key.startsWith("activate_")){a.choice="skip";a.probabilities={active:0,skip:1};}if(corrected&&calls===1)raw.answers.activation.confidence=2;return raw;}});expect(calls).toBe(corrected?2:1);expect(result.council?.batching).toBeUndefined();expect(result.speciesDirectives).toEqual([]);expect(()=>decisions.validateSpeciesDirectives(result,summary().rules!)).not.toThrow();if(corrected){const invalid=structuredClone(result);invalid.council!.correction!.stage="specialists";expect(()=>decisions.validateSpeciesDirectives(invalid,summary().rules!)).toThrow("Invalid correction provenance");}});
it.each(["attempts","stage","usage","unknown_field"])("rejects malformed correction provenance through the wire schema: %s",async(mode)=>{let calls=0;const result=await runCouncil(summary(),{async systemOne(request){calls++;const raw=response(request);if(calls===1)raw.answers.activation.confidence=2;return raw;}});const raw=JSON.parse(JSON.stringify(result));if(mode==="attempts")raw.council.correction.attempts=2;if(mode==="stage")raw.council.correction.stage="authority";if(mode==="usage")raw.council.correction.rejectedUsage.output_tokens=-1;if(mode==="unknown_field")raw.council.correction.hidden="ignored";expect(()=>decisions.validateEvolutionDecision(raw)).toThrow();});
