import {expect,it,vi} from "vitest";
import {decideEvolution} from "./service";
import {createCallBudget} from "./route";
import {createReplay,encodeReplay,decodeReplay} from "@/game/replay";
import {runFreshWithDecisions,runWithDecisionLedger} from "@/game/runtime";
import {snapshotSimulation} from "@/game/world";
import {runCouncil,type CouncilClient} from "./council-service";
import {defaultConfig,hashSetupRequest} from "@/game/setup";
import {createSimulation} from "@/game/world";
import {summarizeEcology,validateSpeciesDirectives} from "@/game/decisions";
function summary(){const config=defaultConfig();config.rules!.council={version:1,members:[{id:"birth_A",responsibility:"birth_policy",scope:"A",activation:"always"},{id:"self_A",responsibility:"self_interaction",scope:"A",activation:"always"}]};return {...summarizeEcology(createSimulation({seed:1,config}),{world:"pond",threat:"drought",reward:"coexist"},"stagnation"),generation:12};}
function response(request:Parameters<CouncilClient["systemOne"]>[0]){return {model:"test-model",usage:{input_tokens:10,output_tokens:2},answers:Object.fromEntries(Object.entries(request.questions).map(([key,q])=>{const keys=Object.keys(q.criteria),selected=key==="selectedPatch"?"none":keys[0];return [key,{type:"choice" as const,choice:selected,confidence:.8,probabilities:Object.fromEntries(keys.map(k=>[k,k===selected?1:0]))}]}))};}
it("corrects invalid runtime orchestration using fresh model evidence and accounts for every call",async()=>{
 const s=summary(),reserve=vi.fn(),requests:Parameters<CouncilClient["systemOne"]>[0][]=[];
 const result=await runCouncil(s,{async systemOne(request){requests.push(request);const raw=response(request);if(requests.length===1)raw.answers.activation.confidence=2;return raw;}},reserve);
 expect(requests).toHaveLength(3);expect(reserve).toHaveBeenCalledTimes(3);expect(result.source).toBe("jev");expect(result.usage).toEqual({input_tokens:30,output_tokens:6});expect(result.council?.calls).toBe(3);expect(result.council).toMatchObject({correction:{stage:"orchestrator",attempts:1,rejectedUsage:{input_tokens:10,output_tokens:2}}});
 expect(requests[1].state).toMatchObject({summary:s,protocol_correction:{issues:expect.arrayContaining([expect.objectContaining({code:"too_big"})])}});expect(requests[1].questions).toEqual(requests[0].questions);expect(()=>validateSpeciesDirectives(result,s.rules!)).not.toThrow();
});
it("corrects only the rejected specialist batch and preserves its newly authored strategy",async()=>{
 const requests:Parameters<CouncilClient["systemOne"]>[0][]=[],reserve=vi.fn();
 const result=await runCouncil(summary(),{async systemOne(request){requests.push(request);const raw=response(request);if(requests.length===2)raw.answers.birth_A__strategy.confidence=2;if(requests.length===3){const a=raw.answers.birth_A__strategy;a.choice="armored";a.probabilities=Object.fromEntries(Object.keys(a.probabilities).map(k=>[k,k==="armored"?.9:.025]));}return raw;}},reserve);
 expect(requests).toHaveLength(3);expect(reserve).toHaveBeenCalledTimes(3);expect(requests[2].questions).toEqual(requests[1].questions);expect(requests[2].state).toMatchObject({protocol_correction:{issues:expect.any(Array)}});expect(result.speciesDirectives![0].strategy).toMatchObject({choice:"armored",probabilities:{armored:.9}});expect(result.council?.correction?.stage).toBe("specialists");expect(result.usage).toEqual({input_tokens:30,output_tokens:6});
});
it("corrects an inactive selected authority through a fresh complete orchestrator response",async()=>{
 let calls=0;const result=await runCouncil(summary(),{async systemOne(request){calls++;const raw=response(request);if(calls===1){raw.answers.selectedPatch.choice="self_A";raw.answers.selectedPatch.probabilities={none:0,self_A:1};raw.answers.activate_self_A.choice="skip";raw.answers.activate_self_A.probabilities={active:0,skip:1};}return raw;}});
 expect(calls).toBe(3);expect(result.council?.selectedPatch).toBe("none");expect(result.council?.correction?.stage).toBe("orchestrator");expect(result.scheduledRuleChange).toBeUndefined();
});
it.each(["persistent","shared"])("abstains after the single shared correction allowance: %s",async(mode)=>{
 let calls=0;const s=summary();const result=await decideEvolution({kind:"evolution",summary:s},{apiKey:"test",client:{async systemOne(request){calls++;const raw=response(request);const key=Object.keys(raw.answers)[0];if(mode==="persistent"||calls===1||calls===3)raw.answers[key].confidence=2;return raw;}}});
 expect(result.source).toBe("fallback");expect(result.fallbackReason).toBe("invalid_response");expect(calls).toBe(mode==="persistent"?2:3);
});
it("never makes the corrective SDK request when its reservation is denied",async()=>{
 let calls=0;const reserve=vi.fn().mockResolvedValueOnce(undefined).mockRejectedValueOnce(new Error("Quota exceeded"));await expect(runCouncil(summary(),{async systemOne(request){calls++;const raw=response(request);raw.answers.activation.confidence=2;return raw;}},reserve)).rejects.toThrow("Quota exceeded");expect(calls).toBe(1);expect(reserve).toHaveBeenCalledTimes(2);
});
it.each(["network unavailable","429 rate limit exceeded"])("does not retry transport errors: %s",async(message)=>{const request=vi.fn().mockRejectedValue(new Error(message));await expect(runCouncil(summary(),{systemOne:request})).rejects.toThrow(message);expect(request).toHaveBeenCalledTimes(1);});
it("rejects unaccountable usage metadata without correction",async()=>{let calls=0;await expect(runCouncil(summary(),{async systemOne(request){calls++;const raw=response(request);raw.usage.input_tokens=-1;return raw;}})).rejects.toThrow();expect(calls).toBe(1);});
it.each(["keys","palette","sum","selection"])("recovers %s protocol errors without altering palettes or ecology",async(mode)=>{let calls=0;const s=summary(),frozen=JSON.stringify(s);const result=await runCouncil(s,{async systemOne(request){calls++;const raw=response(request);if(calls===1){const a=raw.answers.activation;if(mode==="keys")delete raw.answers.duration;if(mode==="palette")a.probabilities.extra=0;if(mode==="sum")a.probabilities[a.choice]=.5;if(mode==="selection"){const other=Object.keys(a.probabilities).find(k=>k!==a.choice)!;a.probabilities[a.choice]=.3;a.probabilities[other]=.7;}}return raw;}});expect(result.source).toBe("jev");expect(calls).toBe(3);expect(JSON.stringify(s)).toBe(frozen);});
it("rejects tampered correction accounting and accepts legacy evidence",async()=>{let calls=0;const s=summary();const repaired=await runCouncil(s,{async systemOne(request){calls++;const raw=response(request);if(calls===1)raw.answers.activation.confidence=2;return raw;}});expect(()=>validateSpeciesDirectives(repaired,s.rules!)).not.toThrow();const changed=structuredClone(repaired);changed.council!.correction!.rejectedUsage.input_tokens++;expect(()=>validateSpeciesDirectives(changed,s.rules!)).toThrow("Council usage mismatch");const count=structuredClone(repaired);count.council!.calls--;expect(()=>validateSpeciesDirectives(count,s.rules!)).toThrow("Incomplete council");const legacy=await runCouncil(s,{async systemOne(request){return response(request);}});expect(legacy.council?.correction).toBeUndefined();expect(()=>validateSpeciesDirectives(legacy,s.rules!)).not.toThrow();});
it("preserves the sixty-call limit across repeated repaired runtime workflows",async()=>{const reserve=createCallBudget(60,60000,()=>0);let calls=0;for(let i=0;i<20;i++){let local=0;await runCouncil(summary(),{async systemOne(request){calls++;local++;const raw=response(request);if(local===1)raw.answers.activation.confidence=2;return raw;}},()=>reserve("client"));}await expect(runCouncil(summary(),{async systemOne(request){calls++;return response(request);}},()=>reserve("client"))).rejects.toThrow("quota exceeded");expect(calls).toBe(60);});
it("replays repaired decisions with identical complete engine snapshots",async()=>{const s=summary(),answers=s.intent;const initial=createSimulation({seed:1,config:{...defaultConfig(),rules:s.rules}});let calls=0;const result=await runFreshWithDecisions(initial,answers,async summary=>{let local=0;return runCouncil(summary,{async systemOne(request){calls++;local++;const raw=response(request);if(local===1)raw.answers.activation.confidence=2;return raw;}});});const before=calls;expect(snapshotSimulation(runWithDecisionLedger(initial,result.ledger,180,answers))).toEqual(snapshotSimulation(result.state));expect(calls).toBe(before);const replay=createReplay({answers,config:initial.config,seed:1,requestHash:hashSetupRequest(answers),ledger:result.ledger});expect(decodeReplay(encodeReplay(replay)).ledger).toEqual(result.ledger);},20000);
