import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
for(const width of [1280,390])for(const theme of ['Light','Dark'])test(`readable ecosystem at ${width}px ${theme}`,async({page},testInfo)=>{
 test.setTimeout(60_000);
 await page.setViewportSize({width,height:850});const errors:string[]=[];const calls:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/judge',r=>{calls.push(r.request().url());return r.abort();});
 await page.clock.install({time:new Date('2026-10-08T04:00:00Z')});await page.clock.pauseAt(new Date('2026-10-08T04:00:01Z'));
 await page.goto('/');await page.getByLabel('Theme').selectOption(theme.toLowerCase());await page.getByRole('button',{name:'Explore deterministic preset'}).click();await page.getByLabel('World policy').selectOption('fixed');await page.getByRole('button',{name:/Seed ecosystem/}).click();await page.getByRole('button',{name:'Pause',exact:true}).click();
 await expect(page.getByTestId('generation')).toHaveText('0 / 180');for(let i=0;i<30;i++)await page.getByRole('button',{name:'Step one generation'}).click();await expect(page.getByTestId('generation')).toHaveText('30 / 180');
 const phase=process.env.LIFEPOT_VISUAL_PHASE??'after';if(phase==='after'){await expect(page.locator('.legend')).toContainText('⬡ Producer');await expect(page.locator('.legend')).toContainText('◇ Omnivore');await expect(page.locator('.legend')).toContainText('local hazard intensity');}
 await page.evaluate(()=>scrollTo(0,0));
 const metrics=await page.evaluate(()=>{const canvas=document.querySelector('canvas.life-canvas') as HTMLCanvasElement;const b=canvas.getBoundingClientRect(),header=document.querySelector('.family-header')!.getBoundingClientRect(),controls=document.querySelector('.controls')!.getBoundingClientRect();const context=canvas.getContext('2d')!,pixels=context.getImageData(0,0,canvas.width,canvas.height).data;const background=Array.from(context.getImageData(0,0,1,1).data);let different=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]!==background[0]||pixels[i+1]!==background[1]||pixels[i+2]!==background[2])different++;return {canvas:{x:b.x,y:b.y,width:b.width,height:b.height,bottom:b.bottom},headerBottom:header.bottom,controlsTop:controls.top,background,different,overflow:document.documentElement.scrollWidth>innerWidth,generation:document.querySelector('[data-testid=generation]')!.textContent,species:Array.from(document.querySelectorAll('.species-focus button')).map(b=>b.textContent)};});
 expect(metrics.overflow).toBe(false);expect(metrics.canvas.y).toBeGreaterThanOrEqual(metrics.headerBottom);expect(metrics.canvas.bottom).toBeLessThanOrEqual(850);expect(metrics.different).toBeGreaterThan(100);if(phase==='after')expect(metrics.background.slice(0,3)).toEqual([2,10,9]);
 const dir=process.env.LIFEPOT_VISUAL_EVIDENCE??testInfo.outputDir;mkdirSync(dir,{recursive:true});const key=`${phase}-${width}x850-${theme.toLowerCase()}-gen30`;writeFileSync(join(dir,key+'.json'),JSON.stringify(metrics,null,2));await page.screenshot({path:join(dir,key+'.png')});await page.locator('canvas.life-canvas').screenshot({path:join(dir,key+'-board.png')});
 await page.getByRole('button',{name:'Inspect living organism',exact:true}).click();await expect(page.getByRole('button',{name:/^Follow founder lineage #/})).toBeVisible();await page.getByRole('button',{name:/^Follow founder lineage #/}).click();await page.getByRole('button',{name:'Resume',exact:true}).click();await page.clock.runFor(650);await expect(page.getByTestId('generation')).not.toHaveText('30 / 180');expect(calls).toEqual([]);expect(errors).toEqual([]);
});
