import { buildRunComparison,type RunComparisonInput } from "@/game/run-reflection";
import { speciesColor } from "@/game/species-colors";
export function RunComparison({before,after,adaptive}:{before:RunComparisonInput;after:RunComparisonInput;adaptive:boolean}){
 const comparison=buildRunComparison(before,after);
 const horizon=Math.max(1,...comparison.before.map(x=>x.generation),...comparison.after.map(x=>x.generation));
 return <section className="run-comparison" aria-label="Previous trial comparison"><h3>Compared with your previous trial</h3>
 <p>Final population: {before.evidence.samples.at(-1)?.population} → {after.evidence.samples.at(-1)?.population}. Peak population: {before.evidence.peakPopulation} → {after.evidence.peakPopulation}.</p>
 <h4>Changed conditions</h4><ul>{comparison.conditionChanges.length?comparison.conditionChanges.map(change=><li key={change.path}>{change.path}: {String(change.before)} → {String(change.after)}</li>):<li>No recorded condition changes.</li>}</ul>
 {comparison.species.map(species=>{const max=Math.max(1,...species.before.map(x=>x??0),...species.after.map(x=>x??0));const segments=(values:(number|null)[])=>{const parts:string[][]=[];let current:string[]=[];values.forEach((value,index)=>{if(value===null){if(current.length)parts.push(current);current=[];}else current.push(`${32+(comparison.generations[index]??0)/horizon*576},${188-(value/max)*156}`);});if(current.length)parts.push(current);return parts.map(part=>part.join(" "));};return <figure key={species.speciesId}><figcaption>Species {species.speciesId} · {species.role} · population by generation</figcaption><svg role="img" aria-label={`Compared population history for species ${species.speciesId}`} className="run-results__graph" viewBox="0 0 640 220"><text x="0" y="32">{max}</text><text x="32" y="212">Gen 0</text><text x="570" y="212">Gen {horizon}</text>{segments(species.before).map((points,index)=><polyline key={`before-${index}`} stroke={speciesColor(species.speciesId)} strokeWidth="2.5" strokeDasharray="6 4" fill="none" points={points}/>)}{segments(species.after).map((points,index)=><polyline key={`after-${index}`} stroke={speciesColor(species.speciesId)} strokeWidth="2.5" fill="none" points={points}/>)}</svg><p>Dashed: previous trial. Solid: this trial.</p><p>First observed extinction: previous {before.evidence.firstExtinction.find(x=>x.speciesId===species.speciesId)?.generation??"not recorded"}; this trial {after.evidence.firstExtinction.find(x=>x.speciesId===species.speciesId)?.generation??"not recorded"}.</p></figure>;})}
 <p>{adaptive?"Adaptive policies may differ between trials. This difference alone does not establish which condition caused it.":"Same initial seed; both trials have no runtime AI interventions. These observations apply only within this toy model."}</p></section>;
}
