import { buildRunComparison,type RunComparisonInput } from "@/game/run-reflection";
import { conditionLabel, conditionValue } from "@/game/condition-labels";
import { speciesColor } from "@/game/species-colors";
import type { EvolutionLedger } from "@/game/decisions";
type Trial = RunComparisonInput & { seed: number | null; policy: "adaptive" | "fixed" | "recorded"; decisions?: EvolutionLedger };
export function RunComparison({before,after}:{before:Trial;after:Trial}){
 const comparison=buildRunComparison(before,after);
 const horizon=Math.max(1,...comparison.before.map(x=>x.generation),...comparison.after.map(x=>x.generation));
 const conditions=comparison.conditionChanges.length;
 const knownSeeds=Number.isFinite(before.seed)&&Number.isFinite(after.seed);
 const sameSeed=knownSeeds&&before.seed===after.seed;
 const seedProvenance=!knownSeeds?"Seed provenance unknown; no same-seed claim is supported.":!sameSeed?"Different initial seeds; outcomes also reflect different starting random states.":`Same initial seed: ${before.seed}.`;
 const design=before.policy==="recorded"||after.policy==="recorded"?"Recorded replay: preserved decisions are not a fresh fixed-rule control. This comparison is exploratory.":before.policy==="adaptive"||after.policy==="adaptive"?"Adaptive exploration: runtime policy decisions may differ. This difference alone does not establish which condition caused it.":conditions===0?"No recorded condition changes: this is a repeat observation, not a changed-condition experiment.":conditions>1?"Multiple conditions changed: this is exploratory, not a single-condition causal comparison.":sameSeed?"Single-condition fixed comparison with the same initial seed; both trials have no runtime AI interventions. Observations apply only within this toy model.":"One recorded condition changed, but starting random states are not controlled; this is exploratory.";
 const beforeJev=before.decisions?.filter(entry=>entry.source==="jev"),afterJev=after.decisions?.filter(entry=>entry.source==="jev");
 const decisions=!beforeJev||!afterJev?"Decision record provenance unavailable; no matching-decision claim is supported.":!beforeJev.length&&!afterJev.length?"No accepted Jev decision records in either trial.":`Accepted Jev decision records ${JSON.stringify(beforeJev)===JSON.stringify(afterJev)?"match":"differ"}: ${beforeJev.length} previous; ${afterJev.length} this trial. Records include timing, observations and model metadata; a record difference is not itself proof of a different executed policy or its effect.`;
 return <section className="run-comparison" aria-label="Previous trial comparison"><h3>Compared with your previous trial</h3>
 <p>Final population: {before.evidence.samples.at(-1)?.population} → {after.evidence.samples.at(-1)?.population}. Peak population: {before.evidence.peakPopulation} → {after.evidence.peakPopulation}.</p>
 <h4>Changed conditions</h4><ul>{comparison.conditionChanges.length?comparison.conditionChanges.map(change=><li key={change.path}>{conditionLabel(change.path)}: {conditionValue(change.path,change.before)} → {conditionValue(change.path,change.after)}</li>):<li>No recorded condition changes.</li>}</ul>
 {comparison.species.map(species=>{const max=Math.max(1,...species.before.map(x=>x??0),...species.after.map(x=>x??0));const segments=(values:(number|null)[])=>{const parts:string[][]=[];let current:string[]=[];values.forEach((value,index)=>{if(value===null){if(current.length)parts.push(current);current=[];}else current.push(`${32+(comparison.generations[index]??0)/horizon*576},${188-(value/max)*156}`);});if(current.length)parts.push(current);return parts.map(part=>part.join(" "));};return <figure key={species.speciesId}><figcaption>Species {species.speciesId} · {species.role} · population by generation</figcaption><svg role="img" aria-label={`Compared population history for species ${species.speciesId}`} className="run-results__graph" viewBox="0 0 640 220"><text x="0" y="32">{max}</text><text x="32" y="212">Gen 0</text><text x="570" y="212">Gen {horizon}</text>{segments(species.before).map((points,index)=><polyline key={`before-${index}`} stroke={speciesColor(species.speciesId)} strokeWidth="2.5" strokeDasharray="6 4" fill="none" points={points}/>)}{segments(species.after).map((points,index)=><polyline key={`after-${index}`} stroke={speciesColor(species.speciesId)} strokeWidth="2.5" fill="none" points={points}/>)}</svg><p>Dashed: previous trial. Solid: this trial.</p><p>First observed extinction: previous {before.evidence.firstExtinction.find(x=>x.speciesId===species.speciesId)?.generation??"not recorded"}; this trial {after.evidence.firstExtinction.find(x=>x.speciesId===species.speciesId)?.generation??"not recorded"}.</p></figure>;})}
 <p>{seedProvenance} Previous policy: {before.policy}; this trial: {after.policy}.</p><p>{design}</p><p>{decisions}</p></section>;
}
