import {expect,it,vi} from "vitest";
import {choice} from "@typesafe-ai/sdk";
import {createReflectHandler} from "./route";
import {reflectRun} from "./service";
import {defaultConfig} from "@/game/setup";
import {createSimulation} from "@/game/world";
import {createRunEvidence} from "@/game/run-evidence";
import * as reflections from "@/game/run-reflection";
type ModelRequest={state:unknown;questions:Record<string,ReturnType<typeof choice>>};
const config=defaultConfig(),evidence=createRunEvidence(createSimulation({seed:1,config}));
function valid(request:ModelRequest){return {model:"fixture",usage:{input_tokens:10,output_tokens:2},answers:Object.fromEntries(Object.entries(request.questions).map(([key,q])=>{const keys=Object.keys(q.criteria),selected=keys[0];return [key,{type:"choice",choice:selected,confidence:.8,probabilities:Object.fromEntries(keys.map(k=>[k,k===selected?1:0]))}]}))};}
it.each(["provider","wire","probabilities","reservation","result"])("identifies the %s reflection boundary without disclosing payload or making another request",async stage=>{const diagnostic=vi.fn(),request=vi.fn(async(input:ModelRequest)=>{if(stage==="provider")throw new Error("private provider payload");const raw=valid(input);if(stage==="wire")raw.usage.input_tokens=-1;if(stage==="probabilities")raw.answers.turningPoint.probabilities[raw.answers.turningPoint.choice]=.5;return raw;});const spy=stage==="result"?vi.spyOn(reflections,"validateReflection").mockImplementationOnce(()=>{throw new Error("private result details");}):undefined;try{const handler=createReflectHandler({limit:async()=>true,reflect:input=>reflectRun(input,{client:{systemOne:request},beforeCall:async()=>{if(stage==="reservation")throw new Error("private reservation details");}}),diagnostic});const response=await handler(new Request("http://localhost/api/reflect",{method:"POST",body:JSON.stringify({evidence,config})}));expect(response.status).toBe(503);expect(diagnostic).toHaveBeenCalledExactlyOnceWith({stage:"reflection",reflectionStage:stage,errorClass:stage==="wire"?"ZodError":"Error"});expect(request).toHaveBeenCalledTimes(stage==="reservation"?0:1);expect(JSON.stringify(diagnostic.mock.calls)).not.toContain("private");}finally{spy?.mockRestore();}});
it("does not retain raw provider errors in classified failures",async()=>{const raw=Object.assign(new Error("private payload"),{payload:"private headers"});const failure=await reflectRun({evidence,config},{client:{async systemOne(){throw raw;}}}).catch(error=>error);expect(failure).toBeInstanceOf(Error);expect(failure).not.toHaveProperty("underlying");expect(failure).not.toHaveProperty("cause");expect(failure).toMatchObject({stage:"provider",errorClass:"Error"});expect(JSON.stringify(failure)).not.toContain("private");expect(failure.message).not.toContain("private");});
it("classifies absent configuration before any reservation",async()=>{const beforeCall=vi.fn();await expect(reflectRun({evidence,config},{apiKey:"",beforeCall})).rejects.toMatchObject({stage:"configuration",errorClass:"Error"});expect(beforeCall).not.toHaveBeenCalled();});
it("does not retain arbitrary provider error names",async()=>{const raw=new Error("private message");raw.name="private class";const failure=await reflectRun({evidence,config},{client:{async systemOne(){throw raw;}}}).catch(error=>error);expect(failure).toMatchObject({stage:"provider",errorClass:"Other"});expect(JSON.stringify(failure)).not.toContain("private");});
