import { TypeSafeClient, choice } from "@typesafe-ai/sdk";
import { conditionLabel, conditionValue } from "@/game/condition-labels";
import { z } from "zod";
import { validateReflection, type RunReflection } from "@/game/run-reflection";
import type { RunEvidence } from "@/game/run-evidence";
import type { LifeConfig } from "@/game/world";
import { ENVIRONMENT_PRESSURES, INTENSITIES, DURATIONS, VOLATILITY_MODES, REGENERATION_MODES } from "@/game/rules";

const ClientResult=z.object({model:z.string().min(1).max(100),usage:z.object({input_tokens:z.number().int().nonnegative(),output_tokens:z.number().int().nonnegative()}).strict(),answers:z.object({turningPoint:z.object({type:z.literal("choice"),choice:z.string(),confidence:z.number().min(0).max(1),probabilities:z.record(z.string(),z.number().min(0).max(1))}).strict(),experiment:z.object({type:z.literal("choice"),choice:z.string(),confidence:z.number().min(0).max(1),probabilities:z.record(z.string(),z.number().min(0).max(1))}).strict()}).strict()}).strict();
type Client={systemOne(request:{state:unknown;questions:Record<string,ReturnType<typeof choice>>}):Promise<unknown>};
const conditionChoices={"rules.environment.pressure":ENVIRONMENT_PRESSURES,"rules.environment.intensity":INTENSITIES,"rules.environment.duration":DURATIONS,"rules.environment.volatility":VOLATILITY_MODES,"rules.environment.regeneration":REGENERATION_MODES,"environment.hazard":["drought","toxin","heat","crowding"],"environment.abundance":["scarce","balanced","rich"],"environment.volatility":["stable","pulsing","chaotic"]} as const;
type ConditionPath=keyof typeof conditionChoices;
const get=(obj:unknown,path:string):unknown=>path.split(".").reduce((v,k)=>v&&typeof v==="object"?(v as Record<string,unknown>)[k]:undefined,obj);
function candidates(config:LifeConfig){return Object.fromEntries(Object.entries(conditionChoices).flatMap(([path,values])=>{const current=get(config,path);return current===undefined?[]:values.filter(v=>v!==current).map(v=>[`${path}=${v}`,`${path}: ${String(current)} → ${v}`])}));}
export async function reflectRun(input:{evidence:RunEvidence;config:LifeConfig},opts:{apiKey?:string;client?:Client;beforeCall?:()=>Promise<void>}={}):Promise<RunReflection>{
 const apiKey=opts.apiKey??process.env.TYPESAFE_API_KEY;if(!opts.client&&!apiKey)throw new Error("Reflection service unavailable");
 const client=opts.client??new TypeSafeClient({apiKey:apiKey!,timeout:7000,retry:{maxRetries:0}});await opts.beforeCall?.();
 const hasDecline=input.evidence.samples.some((s,i)=>i>0&&input.evidence.samples[i-1]!.population>s.population);const points:Record<string,string>={population:"Population trajectory",...(hasDecline?{decline:"Largest observed population decline"}:{}),resource:"Final sampled resource level",...Object.fromEntries(input.evidence.firstExtinction.map(e=>[`extinction:${e.speciesId}`,`Species ${e.speciesId} first reached zero at generation ${e.generation}`])),...Object.fromEntries(input.evidence.lineageExtinction.map(e=>[`family:${e.lineage}`,`Followed family ${e.lineage} reached zero at generation ${e.generation}`])),...Object.fromEntries(input.evidence.ruleEvents.map((e,i)=>[`rule:${i}`,e.kind==="activated"?`Rule event activated at generation ${e.generation}`:`Rule event reverted at generation ${e.generation}`] as const))};
 const options=candidates(input.config);if(!Object.keys(options).length)throw new Error("No supported reflection condition changes available");
 const raw=await client.systemOne({state:{evidence:input.evidence,config:input.config},questions:{turningPoint:choice("Choose the most substantive concrete recorded evidence event or measured trajectory to explain; prefer species/family/rule events when relevant, never invent an event.",points),experiment:choice("Choose one useful supported condition/value alternative that differs from its recorded current value. Select an entry exactly.",options)}});
 const parsed=ClientResult.parse(raw), {turningPoint,experiment}=parsed.answers;
 const check=(a:typeof turningPoint,opts:Record<string,string>)=>{const keys=Object.keys(opts),p=a.probabilities;if(!keys.includes(a.choice)||Object.keys(p).length!==keys.length||keys.some(k=>!(k in p))||Math.abs(Object.values(p).reduce((x,y)=>x+y,0)-1)>.011||p[a.choice]!==Math.max(...Object.values(p)))throw new Error("Invalid reflection decision probabilities");};check(turningPoint,points);check(experiment,options);
 const samples=input.evidence.samples;if(!samples.length)throw new Error("Reflection requires at least one run sample");
 const observations=turningPoint.choice==="decline"?samples.slice(1).map((s,i)=>({s,previous:samples[i]})).filter(x=>x.previous.population>x.s.population).sort((a,b)=>(b.previous.population-b.s.population)-(a.previous.population-a.s.population)).slice(0,2).map(({s,previous})=>({text:`Recorded population fell by ${previous.population-s.population} from generation ${previous.generation} to ${s.generation}.`,evidenceRefs:["population"]})):turningPoint.choice==="resource"?[{text:`Resources were ${samples.at(-1)!.resources} at generation ${samples.at(-1)!.generation}; recorded population was ${samples.at(-1)!.population}.`,evidenceRefs:["population"]}]:turningPoint.choice.startsWith("extinction:")?(()=>{const e=input.evidence.firstExtinction.find(x=>`extinction:${x.speciesId}`===turningPoint.choice)!;return [{text:`Species ${e.speciesId} was first observed at zero at generation ${e.generation}.`,evidenceRefs:[`species:${e.speciesId}`,`extinction:${e.speciesId}`]}]})():turningPoint.choice.startsWith("family:")?(()=>{const e=input.evidence.lineageExtinction.find(x=>`family:${x.lineage}`===turningPoint.choice)!;return [{text:`Followed family ${e.lineage} reached zero at generation ${e.generation}.`,evidenceRefs:[`family:${e.lineage}`]}]})():turningPoint.choice.startsWith("rule:")?(()=>{const index=Number(turningPoint.choice.slice(5)),e=input.evidence.ruleEvents[index]!;return [{text:`A recorded rule ${e.kind} event occurred at generation ${e.generation}.`,evidenceRefs:["population"]}]})():[{text:`At generation ${samples.at(-1)!.generation}, population was ${samples.at(-1)!.population}; peak recorded population was ${input.evidence.peakPopulation}.`,evidenceRefs:["population"]}];
 const [path,value]=experiment.choice.split("=") as [ConditionPath,string];const current=String(get(input.config,path));
 const selectedEvidence=turningPoint.choice.startsWith("family:")?`the followed family ${turningPoint.choice.slice(7)} reaching zero at generation ${input.evidence.lineageExtinction.find(e=>`family:${e.lineage}`===turningPoint.choice)?.generation}`:turningPoint.choice.startsWith("extinction:")?`species ${turningPoint.choice.slice(10)} reaching zero at generation ${input.evidence.firstExtinction.find(e=>`extinction:${e.speciesId}`===turningPoint.choice)?.generation}`:turningPoint.choice==="decline"?"a recorded population decline":"the recorded population and resource trajectory";
 return validateReflection({observations:observations.length?observations:[{text:"No sampled population decline was recorded.",evidenceRefs:["population"]}],nextExperiment:{title:`${conditionLabel(path)}: ${conditionValue(path,current)} → ${conditionValue(path,value)}`,rationale:`Recorded: ${selectedEvidence}. Test ${conditionLabel(path)} (${conditionValue(path,current)} → ${conditionValue(path,value)}); compare whether this pattern recurs. Hypothesis, not a causal conclusion.`,evidenceRefs:[...new Set([...observations.flatMap(o=>o.evidenceRefs),`condition:${path}`])],changes:[{path,value}]},caveat:"Adaptive Jev decisions can differ between runs; aligned comparisons are observational, not proof of cause.",metadata:{source:"typesafe",model:parsed.model,usage:parsed.usage}},input.evidence,input.config);
}
