import {describe,it,expect} from "vitest";
import {reflectRun} from "./service";
import { choice } from "@typesafe-ai/sdk";
type ModelRequest={state:unknown;questions:Record<string,ReturnType<typeof choice>>};
import type {RunEvidence} from "@/game/run-evidence";
import type {LifeConfig} from "@/game/world";
const evidence={followedFamily:null,samples:[{generation:0,population:8,prey:5,predators:3,resources:20,births:0,deaths:0,kills:0,species:[{speciesId:"A",role:"grazer",population:5},{speciesId:"B",role:"hunter",population:3}]},{generation:2,population:4,prey:4,predators:0,resources:18,births:1,deaths:5,kills:2,species:[{speciesId:"A",role:"grazer",population:4},{speciesId:"B",role:"hunter",population:0}]}],peakPopulation:8,firstExtinction:[{speciesId:"B",generation:2}],lineageExtinction:[{lineage:42,generation:2}],ruleEvents:[],observedRuleVersion:1} as RunEvidence;
const config={environment:{abundance:"balanced",distribution:"scattered",hazard:"drought",volatility:"stable"},founders:{balance:"balanced",diversity:"varied",preyStrategy:"generalist",predatorStrategy:"ambush"},fitness:{survive:1,replicate:1,cooperate:1,explore:1,adapt:1},rules:{version:1,environment:{regeneration:"steady",pressure:"drought",volatility:"stable",intensity:"medium",duration:"persistent"},species:[],interactions:[]}} as unknown as LifeConfig;
const mockClient=(choice:string)=>({systemOne:async({questions}:ModelRequest)=>{const answers:Record<string,unknown>={};for(const [key,q] of Object.entries(questions)){const options=q.criteria??{};const first=Object.keys(options)[0];const selected=key==="turningPoint"?choice:first;const probabilities=Object.fromEntries(Object.keys(options).map((k:string)=>[k,k===selected?1:0]));answers[key]={type:"choice",choice:selected,confidence:0.83,probabilities};}return {model:"jev-test",usage:{input_tokens:11,output_tokens:7},answers};}});
describe("reflection service",()=>{
 it("offers substantive species/family evidence and supported changes with metadata",async()=>{let request:ModelRequest={state:null,questions:{}};const client={systemOne:async(r:ModelRequest)=>{request=r;const options=(key:string)=>r.questions[key];const turning="family:42",experiment="rules.environment.intensity=low";const make=(key:string,value:string)=>{const keys=Object.keys(options(key).criteria??{});return {type:"choice",choice:value,confidence:0.83,probabilities:Object.fromEntries(keys.map(k=>[k,k===value?1:0]))}};return {model:"jev-test",usage:{input_tokens:11,output_tokens:7},answers:{turningPoint:make("turningPoint",turning),experiment:make("experiment",experiment)}};}};const result=await reflectRun({evidence,config},{client});expect(request.questions.turningPoint.criteria).toHaveProperty("extinction:B");expect(request.questions.turningPoint.criteria).toHaveProperty("family:42");expect(Object.keys(request.questions.experiment.criteria)).toContain("rules.environment.intensity=low");expect(result.observations[0]?.evidenceRefs).toContain("family:42");expect(result.nextExperiment.changes).toEqual([{path:"rules.environment.intensity",value:"low"}]);expect(result.nextExperiment.rationale).toContain("family 42");expect(result.nextExperiment.rationale).toContain("Pressure intensity");expect(result.nextExperiment.evidenceRefs).toContain("family:42");expect(result.nextExperiment.rationale).toContain("reaching zero");expect(result.metadata).toEqual({source:"typesafe",model:"jev-test",usage:{input_tokens:11,output_tokens:7}});});
 it("names the selected extinct species without including the evidence-key separator",async()=>{const result=await reflectRun({evidence,config},{client:mockClient("extinction:B")});expect(result.nextExperiment.rationale).toContain("species B reaching zero at generation 2");});
 it("rejects a model selection outside the offered candidate palette",async()=>{await expect(reflectRun({evidence,config},{client:mockClient("fabricated")})).rejects.toThrow();});
 it("produces valid reflections for every offered evidence and condition combination",async()=>{let palettes:ModelRequest["questions"]={};const clientFor=(turning?:string,experiment?:string)=>({async systemOne(request:ModelRequest){palettes=request.questions;return {model:"fixture",usage:{input_tokens:10,output_tokens:2},answers:Object.fromEntries(Object.entries(request.questions).map(([key,q])=>{const keys=Object.keys(q.criteria),selected=(key==="turningPoint"?turning:experiment)??keys[0];return [key,{type:"choice",choice:selected,confidence:.8,probabilities:Object.fromEntries(keys.map(k=>[k,k===selected?1:0]))}]}))};}});await reflectRun({evidence,config},{client:clientFor()});const points=Object.keys(palettes.turningPoint.criteria),experiments=Object.keys(palettes.experiment.criteria);for(const point of points)for(const experiment of experiments)await expect(reflectRun({evidence,config},{client:clientFor(point,experiment)})).resolves.toMatchObject({metadata:{source:"typesafe",model:"fixture"}});});
});
